name: dont_forget_about_me
description: Don&#x27;t forget your friends and family

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  path_provider: any
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true